### ISSUE TITLE
docker image missing libsecret

### ISSUE THREAD

**Issue by tbcdebug** [eclipse/xacc#468]
The error message is shown as below. I did install libsecret on my local machine at the default location, i.e., `/usr/lib/x86_64-linux-gnu/libsecret-1.so`.
```
$ docker run --security-opt seccomp=unconfined --init -it -p 3000:3000 xacc/xacc
yarn run v1.13.0
$ /home/dev/node_modules/.bin/theia start /home/dev --hostname=0.0.0.0
internal/modules/cjs/loader.js:800
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:800:18)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/dev/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
Done in 0.58s.
```

**Comment by amccaskey** [comment]
Pushed a fix for this late last night. Please pull latest xacc/xacc image.

**Comment by tbcdebug** [comment]
I tried and the problem is still there fore me. I did use the newer version since 
```
$ docker pull xacc/xacc:latest
latest: Pulling from xacc/xacc
Digest: sha256:55e50820064f5645b1c3d539547c60f316cf4ba76793fc065e296f31d4e47cc8
Status: Image is up to date for xacc/xacc:latest
docker.io/xacc/xacc:latest
```

**Comment by amccaskey** [comment]
Go ahead and run `docker pull xacc/xacc` one more time. The nightly CI server did not have the fix I committed last night, and when it ran overnight, it pushed another buggy image. I just pushed the one I had locally, should work now.

**Comment by tbcdebug** [comment]
OK. I think it's running correctly now.
